# k8s/secret.yaml
# Placeholder Kubernetes Secret for RetroIDE sensitive data
# IMPORTANT: Values must be base64 encoded.
# Use `echo -n 'your-secret-value' | base64` to encode.
# Consider using more secure secret management tools like HashiCorp Vault, Sealed Secrets, etc.

apiVersion: v1
kind: Secret
metadata:
  name: retroide-secrets
type: Opaque # Default type
data:
  # --- API Keys ---
  # echo -n 'your_google_genai_api_key' | base64
  google-genai-api-key: eW91cl9nb29nbGVfZ2VuYWlfYXBpX2tleQ== # Replace with actual base64 encoded key

  # --- Service Secrets ---
  # echo -n 'your-strong-secret-key-for-vault' | base64
  secret-vault-key: eW91ci1zdHJvbmctc2VjcmV0LWtleS1mb3ItdmF1bHQ= # Replace with actual base64 encoded key

  # --- Database Credentials (if applicable) ---
  # echo -n 'your_db_password' | base64
  # db-password: eW91cl9kYl9wYXNzd29yZA==

  # Add other sensitive credentials as needed
